myWebsite:
  component: '@serverless/tencent-website'
  inputs:
    code:
      root: ./
      src: ./dict
      hook: npm run build:prod:en
      index: index.html
      error: index.html
    region: ap-shanghai
    bucketName: test-aungular-1301126429
