MyComponent:
  component: '@serverless/tencent-flask'
  inputs:
    region: ap-shanghai
    functionName: sentry_test
    code: ./
    exclude:
      - .gitignore
      - .git/**
      - node_modules/**
      - .serverless
      - .env
    functionConf:
      timeout: 10
      memorySize: 128
      environment:
        variables:
          TEST: vale
      vpcConfig:
        subnetId: ''
        vpcId: ''
    apigatewayConf:
      protocol: https
      environment: test
