on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted, linux, X64, centOS-sv]
    steps:
    - uses: actions/checkout@v2
    - name: npm install and npm run build
      run: |
        npm ci
        npm run build:prod:en
    - name: serverless deploy
      run: |
        \cp /root/actions-runner/tencent-sls/.env /root/actions-runner/_work/angular8-example-app/angular8-example-app/.env
        sls
