on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --debug
      env:
        SECRET_ID: AKIDllaGSXy8fcCamnoRlJqCi9RWdm18CiES
        SECRET_KEY: hpeEZ3TejtoUv62m9HAoDMBl4rN1mHVS
