on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install and npm run build
      run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: --component=targetComponent deploy
      env:
        TENCENT_SECRET_ID: AKIDllaGSXy8fcCamnoRlJqCi9RWdm18CiES
        TENCENT_SECRET_KEY: hpeEZ3TejtoUv62m9HAoDMBl4rN1mHVS
