on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install and npm run build
      run: |
        npm ci
        npm run build:prod:en
    - name: serverless deploy
      run: |
        pwd
        npm install serverless
        sls --debug
