on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        npm ci
        npm run build:ci
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --debug
      env:
        SECRET_ID: AKIDllaGSXy8fcCamnoRlJqCi9RWdm18CiES
        SECRET_KEY: hpeEZ3TejtoUv62m9HAoDMBl4rN1mHVS
